### ISSUE TITLE
Why you using the old NCalc.NetCore?

### ISSUE THREAD

**Issue by weismantelf** [panoramicdata/PanoramicData.NCalcExtensions#2]
Hello,

why you using the old version of NCalc.NetCore?.
You can use the new CoreCLR-NCalc!

**Comment by weismantelf** [comment]
All test are passing with the CoreCLR-NCalc

**Comment by davidnmbond** [comment]
Pre-release available: https://www.nuget.org/packages/PanoramicData.NCalcExtensions/1.18.11-g36887cb67a
Closing ticket.
